### ISSUE TITLE
I sometimes get completion, sometimes not

### ISSUE THREAD

**Issue by Cloov** [boniatillo-com/PhaserSublimePackage#1]
Hi,

I've had loads of trouble trying to get consistent phaser.io code completion, and have tried many approaches. I thought I had it finally working with your package, but I'm still having problems.

Sometimes the drop-down will show loads of options, sometimes hardly any. Also, I find that populating the drop-down with anything and everything really confuses matters for me - I'd like to customise the drop-down to not show things it has just happened to find in the same document and that kind of thing.

Here are screenshots of what I'm getting at the moment. I'm sure more should be showing. D'you know what I'm doing wrong?

http://i.imgur.com/ZX7Mj49.jpg
http://i.imgur.com/kCaYlKl.jpg

Thanks

**Comment by PhaserEditor2D** [comment]
Hi @Cloov 

From your images I see you are using a code style that is nothing wrong, from a point of view of JavaScript programming, but it really don't help the type inference engine :)

For example, you are coding a Phaser state with this style:

```
GameStates.Game.prototype = {
  create : function () {
   this.<no state methods are going to appear>
  }
}
```

That's fine to develop Phaser but for the inference engine it is impossible to know that `GameStates.Game` is a prototype based on `Phaser.State`.

So, what I recommend is to use other style, and express the "inheritance" of the prototypes:

```
function MyLevel() {
  Phaser.State.call(this);
}

MyLevel.prototype = Object.create(Phaser.State.prototype);
MyLevel.prototype.constructor = MyLevel;

MyLevel.prototype.create = function () {
  this.<it displays all the Phaser.State methods>
};

```

Also I recommend to use jsdoc annotations, like `@type`, `@param`, etc... It provides type information in contexts where it is hard to infer, like in method arguments or return.

Remember, what i am doing is a re-distribution of `tern_for_sublime` with built-in Phaser support and other small modifications, you can check the `tern_for_sublime` issues here:

https://github.com/ternjs/tern_for_sublime/issues

**Comment by PhaserEditor2D** [comment]
By the way, if you are open to diferent editors maybe you can try [Phaser Editor](http://phasereditor.boniatillo.com), it has lot of built-in features for Phaser, including smart coding and custom states and sprites file templates. So it is easier for you to write "auto-competable" code (yet do not expect it to be perfect :) ).

**Comment by Cloov** [comment]
Thanks - I think know what you mean. The code completion works quite well for me in app.js, but that code is inside a window.onLoad function, so I see the difference now. Phaser Editor might be good, but I've only just started developing with HTML5 and JS, so I'll try this for a while first.

**Comment by Cloov** [comment]
The problem I have now is that when I use the above structure, I get the error 'Phaser is not defined'. The format I followed before was taken from existing examples. I want to use your format because I'm getting code completion that way, but I now don't know what to do!

**Comment by PhaserEditor2D** [comment]
If you get that error it is because the phaser lib is not loaded yet. Maybe you can include the phaser lib first  and your javascript files later, in the `index.html` file.

**Comment by Cloov** [comment]
Thanks for your reply. That's what I'm doing:

```
<script scr="lib/phaser/build/phaser.js"></script>
<script src="includes.js"></script>
```

**Comment by PhaserEditor2D** [comment]
So it does not work even in that way?

**Comment by Cloov** [comment]
No. I have my code to instantiate a new Phaser.Game in app.js, like this (I won't post the whole file):

window.onload = function () {
    var game = new Phaser.Game(800, 600, Phaser.AUTO, '');

And then in other files, like game.js and preloader.js, I have the format you posted:

function State_Gameplay() {
    Phaser.State.call(this); // Invoke super constructor, Phaser.State()
    this.preloadBar = null;
};
State_Gameplay.prototype = Object.create(Phaser.State.prototype);
State_Gameplay.prototype.constructor = State_Gameplay;

And in includes.js, I have (and I won't include the include function):

include("app.js");
include("boot.js");
include("preloader.js");
include("mainmenu.js");
include("game.js");

But of course, if I have 'script scr="lib/phaser/build/phaser.js"' before 'script src="includes.js"', then it should be fine, I think... But it's not.

**Comment by Cloov** [comment]
Here are the errors in the browser: http://i.imgur.com/Poq2atV.png

**Comment by PhaserEditor2D** [comment]
Well, I don't know how the `include` function works. Are you using something like RequireJS? Maybe you can try to include the phaser lib also using the `include` function, before the other files.

**Comment by Cloov** [comment]
I stopped using the include function, so now my code looks like this:

```
<script scr="lib/phaser/build/phaser.js"></script>
<script src="app.js"></script>
<script src="boot.js"></script>
<script src="preloader.js"></script>
<script src="mainmenu.js"></script>
<script src="game.js"></script>
```

I still get the same issue :( - Phaser is not defined.

**Comment by PhaserEditor2D** [comment]
Very strange. I recommend to try with a simpler project, with a single JS file, just to see the order Phaser is loaded.

**Comment by Cloov** [comment]
Thanks for your help, it turns out I had script SCR instead of script SRC haha..

**Comment by PhaserEditor2D** [comment]
hehe it happens!
