### ISSUE TITLE
Doesn't work at all

### ISSUE THREAD

**Issue by dzpt** [boniatillo-com/PhaserSublimePackage#2]
Try with this code and nothing works at all

```
function create() {
    var c1 = game.add.graphics(game.world.centerX, 100)
    c1.beginFill(0xFF0000, 1);
    c1.drawCircle(0, 0, 100);
}
```

Always see the (?)

**Comment by PhaserEditor2D** [comment]
Hi @Tom29 

Take a look to this issue:

https://github.com/boniatillo-com/PhaserSublimePackage/issues/1

There I explain why it is not working. Resuming, you should provide "static type information", to help the inference engine to compute the types.

You can follow the "prototype inheritance" way or in the case you wrote, you can annotate the `this` context like this:

```
function create() {
    /** @type {Phaser.State} */
    var self = this;
    var c1 = self.add.graphics(game.world.centerX, 100)
    c1.beginFill(0xFF0000, 1);
    c1.drawCircle(0, 0, 100);
}
```

In the image you can see how it auto-completes the `self.add.` expression. For the `c1` var don't expect too much help, the Graphics type is not well defined in the plugin metadata, but many of the rest of the API should work.

![image](https://cloud.githubusercontent.com/assets/12187299/17662448/834030a4-62b3-11e6-82b7-bcf3344a21b6.png)

**Comment by dzpt** [comment]
Thanks for your reply. I've found the trouble came from adding .tern-project file. I didn't add this file so i can't see the suggestion.

**Comment by PhaserEditor2D** [comment]
Good, I close this then.
