### ISSUE TITLE
(?) on all auto-complete options

### ISSUE THREAD

**Issue by Vine2D** [boniatillo-com/PhaserSublimePackage#3]
I followed the directions as closely as I could and seem to have run into a hiccup;
![lhuw68](https://cloud.githubusercontent.com/assets/21092002/17757473/e257119a-649b-11e6-8645-10c981d70810.png)

I've been tinkering with it for a while and haven't been able to come up with a solution.
Any ideas?

**Comment by PhaserEditor2D** [comment]
Please can you paste here the whole file?

If you don't like the idea, maybe you can create a small demo file and try to reproduce there the same situation.

I really need to see the context :)

**Comment by Vine2D** [comment]
Sure!
Here's the code I'm working with.
It's my first Phaser project so I expect it to be messy or just flatout wrong.
[my phaser game.zip](https://github.com/boniatillo-com/PhaserSublimePackage/files/425652/my.phaser.game.zip)

**Comment by PhaserEditor2D** [comment]
I found a typo: `new Phaser.game(...)` should be `new Phaser.Game(...)` :)

I just fixed it and the autocompletion worked fine:

![image](https://cloud.githubusercontent.com/assets/12187299/17787344/bec1ed20-6556-11e6-96de-a6831d648e53.png)

![image](https://cloud.githubusercontent.com/assets/12187299/17787375/dd03b16a-6556-11e6-8cee-4d1ae33e02fe.png)

Also remember to add a `.tern-project` file in the root of your project:

`.tern-project` file:

```
{
  "libs": ["browser"],
  "plugins" : {
    "phaser" : {},
    "doc_comment": {}
  }
}
```

**Comment by Vine2D** [comment]
Hmm, still a no-go.
I'll try the whole process from scratch and see if that resolves anything.
![image](https://cloud.githubusercontent.com/assets/21092002/17788821/4b63248c-6544-11e6-85e4-21c697afac53.png)

**Comment by PhaserEditor2D** [comment]
Please try with this project:

https://github.com/boniatillo-com/PhaserSublimePackage/tree/master/demo/sublime-projects/phaser

and tell me if it works.

**Comment by Vine2D** [comment]
After a fresh reinstall and some tinkering I've gotten it to work, example project works as well (:

**Comment by PhaserEditor2D** [comment]
Great! Now to make games! :)
